[project]
name = "aoc2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.0",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "ANN", "B"]
